services:
  api:
    build: ./backend
    container_name: stocktracker_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
    restart: unless-stopped
