services:
  api:
    build: ./backend
    container_name: stocktracker_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: stocktracker_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped
