"""create market data tables

Revision ID: 24a3cedff551
Revises: dc35a99b6212
Create Date: 2026-05-15 01:14:18.097302

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '24a3cedff551'
down_revision = 'dc35a99b6212'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'data_type', 'source_provider', name='uq_market_data_cache_key')
    )
    op.create_index(op.f('ix_market_data_cache_data_type'), 'market_data_cache', ['data_type'], unique=False)
    op.create_index(op.f('ix_market_data_cache_symbol'), 'market_data_cache', ['symbol'], unique=False)
    op.create_table('company_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_security_id'), 'company_profiles', ['security_id'], unique=True)
    op.create_table('dividend_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividend_events_pay_date'), 'dividend_events', ['pay_date'], unique=False)
    op.create_index(op.f('ix_dividend_events_security_id'), 'dividend_events', ['security_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'price_date', 'source_provider', name='uq_price_history_security_date_source')
    )
    op.create_index(op.f('ix_price_history_price_date'), 'price_history', ['price_date'], unique=False)
    op.create_index(op.f('ix_price_history_security_id'), 'price_history', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_security_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_price_date'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_dividend_events_security_id'), table_name='dividend_events')
    op.drop_index(op.f('ix_dividend_events_pay_date'), table_name='dividend_events')
    op.drop_table('dividend_events')
    op.drop_index(op.f('ix_company_profiles_security_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_market_data_cache_symbol'), table_name='market_data_cache')
    op.drop_index(op.f('ix_market_data_cache_data_type'), table_name='market_data_cache')
    op.drop_table('market_data_cache')
    # ### end Alembic commands ###
