"""create portfolio snapshots

Revision ID: da71bbc010e2
Revises: 6b1ae6da81b2
Create Date: 2026-05-17 19:26:47.951897

"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'da71bbc010e2'
down_revision = '6b1ae6da81b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('market_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_basis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('unrealized_gain_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monthly_dividend_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('annual_dividend_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('holdings_count', sa.Integer(), nullable=False),
    sa.Column('watchlist_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'snapshot_date', name='uq_portfolio_snapshot_account_date')
    )
    op.create_index(op.f('ix_portfolio_snapshots_account_id'), 'portfolio_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_snapshot_date'), 'portfolio_snapshots', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_snapshots_snapshot_date'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_account_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
